version: "3.9"

services:
  frontend:
    build: .
    container_name: nordic_frontend
    restart: always
    expose:
      - "3000"
    networks:
      - projhouse-net

networks:
  projhouse-net:
    external: true