version: '3.9'

services:
  frontend:
    container_name: nordic_frontend
    build: .
    restart: always
    expose:
      - "3000"
    networks:
      - projhouse-net

networks:
  projhouse-net:
    external: true
